### ISSUE TITLE
DB Maken Tabel Vraag

### ISSUE THREAD

**Issue by w1jnands44** [ivohulsman/IProject23#13]

**Comment by raymondvansomeren** [comment]
[DLL tabel Vraag.zip](https://github.com/ivohulsman/IProject23/files/972804/DLL.tabel.Vraag.zip)

**Comment by ivohulsman** [comment]
<?php
// Variabelen
$servername = "localhost";
$uid = "sa";
$pwd = "klopklop";
$database = "Fletnix";

//Maak de benodigde variablelen leeg
$conn = null;
$sql = null;
$results = null;

	// Connectie
    try {
        $conn = new PDO("sqlsrv:server=$servername;database=$database;ConnectionPooling=0", $uid, $pwd);
        $conn->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $conn->setAttribute(PDO::SQLSRV_ATTR_DIRECT_QUERY, true);
	
    } catch( PDOException $e ){
        echo "Error connecting to SQL Server";
        echo $e->getMessage();
        exit();

    }

?>

**Comment by w1jnands44** [comment]
Goedgekeurd
