### ISSUE TITLE
Onderzoek Front End Framework

### ISSUE THREAD

**Issue by ivohulsman** [ivohulsman/IProject23#2]
Eind Versie die geverifieerd moet worden:
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/946508/Front-end.Frameworks.docx)

**Comment by w1jnands44** [comment]
[Onderzoek frontend framework.docx](https://github.com/ivohulsman/IProject23/files/941343/Onderzoek.frontend.framework.docx)

**Comment by w1jnands44** [comment]
![mspaint_2017-04-20_10-21-09](https://cloud.githubusercontent.com/assets/3726729/25220794/313f7378-25b3-11e7-89fd-556d36c3c7b9.png)

**Comment by AhmetFUsta** [comment]
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/941614/Front-end.Frameworks.docx)

**Comment by AhmetFUsta** [comment]
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/941620/Front-end.Frameworks.docx)

**Comment by w1jnands44** [comment]
![chrome_2017-04-20_10-53-25](https://cloud.githubusercontent.com/assets/3726729/25222102/bf22db04-25b7-11e7-8247-b664c4a00b43.png)

**Comment by AhmetFUsta** [comment]
![screenshot 2017-04-20 11 16 39](https://cloud.githubusercontent.com/assets/27206036/25223184/edd67a20-25ba-11e7-9b95-0faf90e4d6ec.png)

**Comment by AhmetFUsta** [comment]
![screenshot 2017-04-20 12 39 33](https://cloud.githubusercontent.com/assets/27206036/25226799/7da51e4e-25c6-11e7-9400-88ff0c38f208.png)

**Comment by AhmetFUsta** [comment]
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/942392/Front-end.Frameworks.docx)
Deze versie moet gelezen worden door de groepsleden zodat we samen een besluit kunnen vormen om welke framework we gaan gebruiken en dan kunnen we de inleiding en conclusie ook maken

**Comment by w1jnands44** [comment]
![winword_2017-04-21_09-58-14](https://cloud.githubusercontent.com/assets/3726729/25268465/1754a516-2679-11e7-85a2-1427b9f8d6ee.png)

**Comment by w1jnands44** [comment]
[matrix.docx](https://github.com/ivohulsman/IProject23/files/946382/matrix.docx)

**Comment by w1jnands44** [comment]
[inleiding.docx](https://github.com/ivohulsman/IProject23/files/946449/inleiding.docx)

**Comment by AhmetFUsta** [comment]
Eind Versie:
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/946508/Front-end.Frameworks.docx)

**Comment by AhmetFUsta** [comment]
[Front-end Frameworks.docx](https://github.com/ivohulsman/IProject23/files/946517/Front-end.Frameworks.docx)
Door Ivo verbeterde versie.

**Comment by ivohulsman** [comment]
Gecontroleerd.
