### ISSUE TITLE
PHP Maken template (header/footer pagina's)

### ISSUE THREAD

**Issue by w1jnands44** [ivohulsman/IProject23#21]

**Comment by w1jnands44** [comment]
Header en footer zijn gemaakt. Deze zijn nog vrij kaal en zullen later aangevuld worden.

Daarnaast heb ik een page index gemaakt die de header en footer includen.

Voor het maken van een nieuwe pagina begin je met de code hieronder:

<?php
require 'header.php';

// CONTENT HERE

require 'footer.php';
?>

**Comment by ivohulsman** [comment]
Gecontroleerd.
