### ISSUE TITLE
Plan van Aanpak

### ISSUE THREAD

**Issue by ivohulsman** [ivohulsman/IProject23#3]
[Plan van Aanpak v1.1 Ivo Hulsman.docx](https://github.com/ivohulsman/IProject23/files/933739/Plan.van.Aanpak.v1.1.Ivo.Hulsman.docx)

**Comment by tombolk** [comment]
[Plan van Aanpak (eerste individuele versie).docx](https://github.com/ivohulsman/IProject23/files/933742/Plan.van.Aanpak.eerste.individuele.versie.docx)

**Comment by raymondvansomeren** [comment]
[Plan van aanpak Raymond van Someren.docx](https://github.com/ivohulsman/IProject23/files/933743/Plan.van.aanpak.Raymond.van.Someren.docx)

**Comment by STRINIX** [comment]
[Plan van aanpak.docx](https://github.com/ivohulsman/IProject23/files/933744/Plan.van.aanpak.docx)

**Comment by w1jnands44** [comment]
[PVA I-Project raw.docx](https://github.com/ivohulsman/IProject23/files/933746/PVA.I-Project.raw.docx)

**Comment by tombolk** [comment]
Concept versie volledig uitgewerkt. 
[Plan van Aanpak Groepsversie Concept.pdf](https://github.com/ivohulsman/IProject23/files/942853/Plan.van.Aanpak.Groepsversie.Concept.pdf)

**Comment by tombolk** [comment]
Word versie 
[Plan van Aanpak Groepsversie Concept.docx](https://github.com/ivohulsman/IProject23/files/943267/Plan.van.Aanpak.Groepsversie.Concept.docx)

**Comment by ivohulsman** [comment]
Diverse spelfouten gecorrigeerd, en wat grammaticale dingen naar mening veranderd. Graag een 2e controle. Ook graag de opmaak vergelijken, ik heb hem bewerkt in Libre. @tombolk 

[Plan van Aanpak Groepsversie.pdf](https://github.com/ivohulsman/IProject23/files/943677/Plan.van.Aanpak.Groepsversie.pdf)

**Comment by ivohulsman** [comment]
[Plan van Aanpak Groepsversie.zip](https://github.com/ivohulsman/IProject23/files/946359/Plan.van.Aanpak.Groepsversie.zip)

**Comment by raymondvansomeren** [comment]
PvA met markeringen en notities (nog aanpassen)
[Plan.van.Aanpak.Groepsversie.pdf](https://github.com/ivohulsman/IProject23/files/946452/Plan.van.Aanpak.Groepsversie.pdf)

**Comment by tombolk** [comment]
[Plan van Aanpak Groepsversie Concept V1.1.pdf](https://github.com/ivohulsman/IProject23/files/946516/Plan.van.Aanpak.Groepsversie.Concept.V1.1.pdf)
Eerste concept versie klaar om verstuurd te worden
