### ISSUE TITLE
Defenition of Done

### ISSUE THREAD

**Issue by raymondvansomeren** [ivohulsman/IProject23#6]
[Defenition of Done.docx](https://github.com/ivohulsman/IProject23/files/943091/Defenition.of.Done.docx)

**Comment by tombolk** [comment]
Aangepaste versie met wat eigen ingeving erbij

[BIJLAGE I Defenition of Done Concept.pdf](https://github.com/ivohulsman/IProject23/files/943155/BIJLAGE.I.Defenition.of.Done.Concept.pdf)

**Comment by tombolk** [comment]
Eerste Concept versie om met de scrum master te reviewen
[BIJLAGE I Defenition of Done Concept.docx](https://github.com/ivohulsman/IProject23/files/943247/BIJLAGE.I.Defenition.of.Done.Concept.docx)

**Comment by ivohulsman** [comment]
Gecontroleerd en gezamelijk met @tombolk gecorrigeerd. Issue closed.
