### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by AhmetFUsta** [ivohulsman/IProject23#8]
Hierin komt ons algemene backlog van alle sprints. De product owner kiest per sprint welke van items van de backlog we per sprint gaan realiseren en daar maken we dan een aparte sprint backlog voor.

**Comment by raymondvansomeren** [comment]
begin:
[product backlog.docx](https://github.com/ivohulsman/IProject23/files/946620/product.backlog.docx)

**Comment by tombolk** [comment]
[Product Backlog Concept V1.0.docx](https://github.com/ivohulsman/IProject23/files/946665/Product.Backlog.Concept.V1.0.docx)
[Product Backlog Concept V1.0.pdf](https://github.com/ivohulsman/IProject23/files/946666/Product.Backlog.Concept.V1.0.pdf)

Eerste concept versie voor opsturen naar scrum master en product owner
